### ISSUE TITLE
tic-tac-toe

### ISSUE THREAD

**Issue by Harshit-Poddar90** [sreyan-ghosh/parsemail#1]
I am a beginner!! so I would like to add my small project under hacktoberfest2021.

**Comment by Harshit-Poddar90** [comment]
pls assign me

**Comment by sreyan-ghosh** [comment]
Hi @Harshit-Poddar90, this is not a generic contribution repository. This means you cannot post a tic-tac-toe project under this repo. The purpose of the repo is to send bulk mails after getting the email addresses from an excel file. I am, therefore, closing this issue. Please go through the [`README.md`](https://github.com/sreyan-ghosh/parsemail/blob/master/README.md) file for issues you can contribute to.

**Comment by Harshit-Poddar90** [comment]
Ohk np
